# Generated by Django 3.1.3 on 2020-12-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
