# Generated by Django 3.1.3 on 2020-12-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201225_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
